---
# tasks file for server_role_redis_server
    - name: Install redis on Rocky Linux
      ansible.builtin.dnf:
        name: redis
        state: present
      when: "'server_role_redis_server' in group_names and ansible_facts['distribution'] == 'Rocky'"
# Tasks for Frontend Servers
    - name: Install nginx on Rocky Linux
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: "'server_role_redis_server' in group_names and ansible_facts['distribution'] == 'Rocky'"
    # Create index.html using a template
    - name: create index.html
      ansible.builtin.template:
        src: index.html.j2 # Ensure you have the file "index.html.j2" in your templates directory
        dest: /var/www/html/index.html
      when: "'server_role_redis_server' in group_names and ansible_facts['distribution'] == 'Rocky'"
    # Create nginx configuration file
    - name: create nginx configuration
      ansible.builtin.copy:
        src: default.conf # Ensure you have the file "default.conf" in your files directory
        dest: /etc/nginx/sites-available/default
      when: "'server_role_redis_server' in group_names and ansible_facts['distribution'] == 'Rocky'"
    # Enable nginx configuration by creating a symlink
    - name: enable nginx configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      when:  "'server_role_redis_server' in group_names and ansible_facts['distribution'] == 'Rocky'"
